name: ci

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'feat/*'
      - 'fix/*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        run: npm ci

      - name: Audit Dependencies
        run: npm audit --production

      - name: Linter
        run: npm run lint

      - name: Unit Tests
        run: npm run test