name: docker

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - 'release'

env:
  imageName: 'julieio/hello'
  imageTag: 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Tag with 'latest'
        if: github.ref == 'refs/heads/main'
        run: |
          echo "imageTag=latest" >> $GITHUB_ENV

      - name: Tag with app version
        if: github.ref == 'refs/heads/release'
        run: |
          echo "imageTag=$(npm run --silent app-version)" >> $GITHUB_ENV

      - name: Debug - Image Tag
        run: |
          echo "${{ env.imageTag }}"

      - name: Docker - Build
        run: |
          docker build -t ${{ env.imageName }}:${{ env.imageTag }} .

      - name: Scan - Snyk Vulnerability Scanner
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.imageName }}:${{ env.imageTag }}
          args: --file=Dockerfile

      - name: Scan - Publish Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

      - name: Docker Hub - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker - Push
        id: docker_push
        run: |
          docker push ${{ env.imageName }}:${{ env.imageTag }}

      - name: Debug - Image digest
        run: echo ${{ steps.docker_push.outputs.digest }}